export const qk = {
  workers: ["workers"] as const,
  trees: ["trees"] as const,
  careLogs: ["careLogs"] as const,
  cycles: ["cycles"] as const,
  events: ["events"] as const,
  expenses: ["expenses"] as const,
  locations: ["locations"] as const,
  customers: ["customers"] as const,
  sales: ["sales"] as const,
  workLogs: ["workLogs"] as const,
  payroll: ["payroll"] as const,
  users: ["users"] as const,
  farm: ["farm"] as const,
  audit: ["audit"] as const,
  tasks: ["tasks"] as const,
};
